// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddFormulePackageController from "./add_formule_package_controller"
application.register("add-formule-package", AddFormulePackageController)

import AddGalleryPicturesController from "./add_gallery_pictures_controller"
application.register("add-gallery-pictures", AddGalleryPicturesController)

import AddProfilePictureController from "./add_profile_picture_controller"
application.register("add-profile-picture", AddProfilePictureController)

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import BottomController from "./bottom_controller"
application.register("bottom", BottomController)

import ClientController from "./client_controller"
application.register("client", ClientController)

import CopyToClipboardController from "./copy_to_clipboard_controller"
application.register("copy-to-clipboard", CopyToClipboardController)

import DatetimeController from "./datetime_controller"
application.register("datetime", DatetimeController)

import DemoController from "./demo_controller"
application.register("demo", DemoController)

import DispoController from "./dispo_controller"
application.register("dispo", DispoController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormToggleController from "./form_toggle_controller"
application.register("form-toggle", FormToggleController)

import FormuleController from "./formule_controller"
application.register("formule", FormuleController)

import FullScreenGalleryController from "./full_screen_gallery_controller"
application.register("full-screen-gallery", FullScreenGalleryController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageAppearController from "./image_appear_controller"
application.register("image-appear", ImageAppearController)

import LeftNavbarController from "./left_navbar_controller"
application.register("left-navbar", LeftNavbarController)

import MapController from "./map_controller"
application.register("map", MapController)

import NotesController from "./notes_controller"
application.register("notes", NotesController)

import OnboardingLoaderController from "./onboarding_loader_controller"
application.register("onboarding-loader", OnboardingLoaderController)

import ReservationController from "./reservation_controller"
application.register("reservation", ReservationController)

import RevenuController from "./revenu_controller"
application.register("revenu", RevenuController)

import ScrollNavController from "./scroll_nav_controller"
application.register("scroll-nav", ScrollNavController)

import ScrollToElementController from "./scroll_to_element_controller"
application.register("scroll-to-element", ScrollToElementController)

import ScrollToElementUpController from "./scroll_to_element_up_controller"
application.register("scroll-to-element-up", ScrollToElementUpController)

import ShareLinkController from "./share_link_controller"
application.register("share-link", ShareLinkController)

import SlotSelectorController from "./slot_selector_controller"
application.register("slot-selector", SlotSelectorController)

import Step2Controller from "./step2_controller"
application.register("step2", Step2Controller)

import VoirPlusBackController from "./voir_plus_back_controller"
application.register("voir-plus-back", VoirPlusBackController)

import VoirPlusBtnController from "./voir_plus_btn_controller"
application.register("voir-plus-btn", VoirPlusBtnController)

import VoirPlusController from "./voir_plus_controller"
application.register("voir-plus", VoirPlusController)

import WeekToggleController from "./week_toggle_controller"
application.register("week-toggle", WeekToggleController)

import WeekdaySelectorController from "./weekday_selector_controller"
application.register("weekday-selector", WeekdaySelectorController)
