// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BottomController from "./bottom_controller"
application.register("bottom", BottomController)

import ClientController from "./client_controller"
application.register("client", ClientController)

import CopyToClipboardController from "./copy_to_clipboard_controller"
application.register("copy-to-clipboard", CopyToClipboardController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FormuleController from "./formule_controller"
application.register("formule", FormuleController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import ReservationController from "./reservation_controller"
application.register("reservation", ReservationController)

import RevenuController from "./revenu_controller"
application.register("revenu", RevenuController)

import ShareLinkController from "./share_link_controller"
application.register("share-link", ShareLinkController)
