meta_name: "ChuckApp"
meta_title: "Créé ton site et gère ton activité"
meta_description: "Un site web à ton image généré en 2 minutes : gestion de ton agenda, gestion de tes réservations, paiement en ligne et avis clients ..."
meta_image: "Add-a-heading-18.png" # should exist in `app/assets/images/`
